export const conferencesList = [
    {
        "name": "JAMstack Conf",
        "city": "London",
        "country": "England",
        "continent": "Europe",
        "start_date": "09.07.2019",
        "end_date": "10.07.2019",
        "url": "https://jamstackconf.com/london/",
        "category": "frontend",
        "lat": 51.50853,
        "lng": -0.12574,
    },
    {
        "name": "CSSCamp Barcelona",
        "city": "Barcelona",
        "country": "Spain",
        "continent": "Europe",
        "start_date": "17.07.2019",
        "end_date": "17.07.2019",
        "url": "https://csscamp.tech/",
        "category": "frontend",
        "lat": 41.38879,
        "lng": 2.15899,
    },
    {
        "name": "JSCamp Barcelona",
        "city": "Barcelona",
        "country": "Spain",
        "continent": "Europe",
        "start_date": "18.07.2019",
        "end_date": "19.07.2019",
        "url": "https://jscamp.tech/",
        "category": "frontend",
        "lat": 41.38879,
        "lng": 2.15899,
    },
];
